services:
    netgen_information_collection.action.registry:
        class: Netgen\Bundle\InformationCollectionBundle\Action\ActionRegistry
        arguments:
            - "@ezpublish.config.resolver"
            - "@logger"
        calls:
            - [setDebug, ['%kernel.debug%']]

    netgen_information_collection.action.db:
        class: Netgen\Bundle\InformationCollectionBundle\Action\DatabaseAction
        arguments:
            - '@netgen_information_collection.factory.field_data'
            - '@netgen_information_collection.repository.ez_info_collection'
            - '@netgen_information_collection.repository.ez_info_collection_attribute'
            - '@ezpublish.api.repository'
        tags:
            - { name: netgen_information_collection.action, alias: database, priority: 300 }

    netgen_information_collection.action.email:
        class: Netgen\Bundle\InformationCollectionBundle\Action\EmailAction
        arguments:
            - '@netgen_information_collection.factory.email_data'
            - '@netgen_information_collection.mailer'
        tags:
            - { name: netgen_information_collection.action, alias: email }

    netgen_information_collection.action.auto_responder:
        class: Netgen\Bundle\InformationCollectionBundle\Action\AutoResponderAction
        arguments:
            - '@netgen_information_collection.factory.auto_responder_data'
            - '@netgen_information_collection.mailer'
        tags:
            - { name: netgen_information_collection.action, alias: auto_responder }
