services:
    netgen_information_collection.controller.collect_information:
        class: Netgen\Bundle\InformationCollectionBundle\Controller\CollectInformation
        public: true
        tags:
            - { name: controller.service_arguments }
        calls:
            - [setContainer, ['@service_container']]

    netgen_information_collection.controller.admin:
        class: Netgen\Bundle\InformationCollectionBundle\Controller\Admin\AdminController
        parent: Ibexa\Core\MVC\Symfony\Controller\Controller
        public: true
        arguments:
            - "@netgen_information_collection.api.service"
            - "@netgen_information_collection.anonymizer.service"
            - "@ibexa.api.service.content"
            - "@ibexa.config.resolver"
            - "@translator"
            - '@netgen_information_collection.factory.field_data'
            - '@netgen_information_collection.repository.ez_info_collection'
            - '@netgen_information_collection.repository.ez_info_collection_attribute'
            - '@netgen_information_collection.form.builder'

    netgen_information_collection.controller.export.export:
        class: Netgen\Bundle\InformationCollectionBundle\Controller\Admin\Export\Export
        public: true
        arguments:
            - "@ibexa.api.service.content"
            - "@netgen_information_collection.service.exporter"
            - "@netgen_information_collection.core.export.registry"
        tags:
            - { name: controller.service_arguments }
        calls:
            - [setContainer, ["@service_container"]]

    netgen_information_collection.controller.tree:
        class: Netgen\Bundle\InformationCollectionBundle\Controller\Admin\TreeController
        parent: Ibexa\Core\MVC\Symfony\Controller\Controller
        public: true
        arguments:
            - "@netgen_information_collection.api.service"
            - "@translator"
            - "@router"
